[config]
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell/quickshell.qml"
output_path = "~/.config/quickshell/modules/shared/Matugen.qml"

[templates.kvantum_kvconfig]
input_path = './templates/kvantum/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = './templates/kvantum/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'
