gui:
  theme:
    activeBorderColor:
      - "#61AFEF" # blue
      - bold

    inactiveBorderColor:
      - "#3E4452" # bg2

    optionsTextColor:
      - "#56B6C2" # cyan

    selectedLineBgColor:
      - "#282C34" # bg1

    selectedRangeBgColor:
      - "#2C323C" # bg1/bg2

    cherryPickedCommitFgColor:
      - "#56B6C2" # cyan

    cherryPickedCommitBgColor:
      - "#1E2127" # bg_d

    unstagedChangesColor:
      - "#E5C07B" # yellow

    defaultFgColor:
      - "#ABB2BF" # fg

    searchingActiveBorderColor:
      - "#C678DD" # purple

  nerdFontsVersion: "3"
