gui:
  theme:
    activeBorderColor:
      - "#78824B"
      - bold

    inactiveBorderColor:
      - "#666666"

    optionsTextColor:
      - "#C9A554"

    selectedLineBgColor:
      - "#1C1C1C"

    selectedRangeBgColor:
      - "#43492A"

    cherryPickedCommitFgColor:
      - "#5F875F"

    cherryPickedCommitBgColor:
      - "#222222"

    unstagedChangesColor:
      - "#BB7744"

    defaultFgColor:
      - "#C2C2B0"

    searchingActiveBorderColor:
      - "#5F875F"

  nerdFontsVersion: "3"
