# Change prefix and remove r binding
set -g prefix C-m

# support for image.nvim from 3rd
set -gq allow-passthrough on
set -g visual-activity off
set -ga terminal-overrides ",xterm-256color:Tc"
set-window-option -g allow-rename off
set-window-option -g automatic-rename off

# fix zsh bindings
set -g xterm-keys on

# enable mouse support
set -g mouse on

source ~/.config/tmux/conf.d/binding.conf
source ~/.config/tmux/conf.d/theme.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'noscript/tmux-mighty-scroll'

run '~/.tmux/plugins/tpm/tpm'
