# GENERAL
general {
  hide_cursor = true
}

cursor {
 no_hardware_cursor = 1 
}

# BACKGROUND
background {
  monitor =
	path = $HOME/.config/hypr/assets/lockscreen.png
	blur_passes = 2
	contrast = 0.8916
	brightness = 0.5172
	vibrancy = 1.5696	
}


# TIME
label {
  monitor =
  text = $TIME
  color = rgba(239, 113, 140, 1.00)
  font_size = 140
  font_family = SF Pro Rounded Bold
  position = 0, -220
  halign = center
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = rgba(239, 113, 140, 1.00)
  font_size = 25
  font_family = SF Pro Rounded Medium
  position = 0, -180
  halign = center
  valign = top
}

# FINGERPRINT
{
  monitor = "";
  text = "$FPRINTPROMPT"
  color = rgba(239, 113, 140, 1.00)
  font_size = 14
  font_family = SF Pro Display Regular
  position = "0, -107"
  halign = "center"
  valign = "center
}

# USER-BOX
shape {
	monitor =
	size = 350, 80
	shape = circle
	position = -100, 100
	rounding = 16
	halign = right
	valign = bottom
	color = rgba(0, 0, 0, 0.6)
	border_size = 3
	border_color = rgba(38, 50, 76, 0.2)
}

#USER
label {
	monitor =
	text =  $DESC
	color = #a9b1d6
	font_size = 20
	outline_thickness = 2
	color = rgb(205, 214, 244)
	font_family = JetBrainsMono Nerd Font Propo
	position = -150, 125
	halign = right
	valign = bottom
}

# INPUT FIELD
input-field {
    monitor =
    size = 600, 80
    outline_thickness = 3
		rounding = 100
		dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
		dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(38, 50, 76, 0.2)
		inner_color = rgba(00, 00, 00, 0.8)
    font_color = rgb(205, 214, 244)
    fade_on_empty = false
    font_family = SF Pro Display Italic
		font_size = 25
    placeholder_text = <span foreground="##ef718c">Password</span>
    hide_input = false
    position = 0, 30
    halign = center
    valign = center
}
