source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/workspace.conf
source = ~/.config/hypr/config/binding.conf
source = ~/.config/hypr/config/animation.conf
source = ~/.config/hypr/config/decoration.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/rule.conf
source = ~/.config/hypr/config/general.conf

debug {
	disable_logs = false
	damage_tracking = false
}


gesture {
	gesture = 3, vertical, workspace, scale: 0.5
	gesture = 3, horizontal, scrollMove
	gesture = 4, vertical, dispatcher, exec, qs ipc call windowSwitcher toggle
}

gestures {
	workspace_swipe_distance = 700
		workspace_swipe_cancel_ratio = 0.15
		workspace_swipe_min_speed_to_force = 5
		workspace_swipe_direction_lock = true
		workspace_swipe_direction_lock_threshold = 10
		workspace_swipe_create_new = true
}
