# █ █ █▄█ █▀█ █▀█ █   █▀█ █▀▀ █▄▀
# █▀█  █  █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █ █

$WALLPAPER = $HOME/.config/hypr/assets/wallpaper.png
$PROFILE = $HOME/.config/hypr/assets/profile.jpg



# GENERAL
general {
	no_fade_in = true
	grace = 1
	disable_loading_bar = false
	hide_cursor = true
	ignore_empty_input = true
	text_trim = true
}

# BACKGROUND
background {
	monitor =
	path = $WALLPAPER
	blur_passes = 2
	contrast = 0.8916
	brightness = 0.7172
	vibrancy = 0.1696
	vibrancy_darkness = 0
}

# PROFILE
image {
	monitor =
	path = $PROFILE
	size = 150
	rounding = -1
	border_size = 3
	border_color = rgb(221, 221, 221)
	rotate = 0
	position = 0, 10%
	halign = center
	valign = center
}

# USERNAME
label {
	monitor =
	text = cmd[update:1000] echo -e "<i> $DESC </i>"
	color = rgba(255, 255, 255, 0.8)
	font_size = 30
	font_family = JetBrainsMono Nerd Font
	position = 0, 4%
	halign = center
	valign = center
	zindex = 5
}

# INPUT FIELD
input-field {
	monitor =
		size = 10%, 3%
		outline_thickness = 1
		outer_color = rgba(0, 0, 0, 0)
		dots_size = 0.2
		dots_spacing = 1
		dots_center = true
		inner_color = rgba(255, 255, 255, 0.1)
		font_color = rgba(200, 200, 200, 0.5)
		fade_on_empty = false
		placeholder_text =<i>Login</i>
		hide_input = false
		position = 0,0
		halign = center
		valign = center
		zindex = 20
}
