source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/permission.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/workspace.conf
source = ~/.config/hypr/config/binding.conf
source = ~/.config/hypr/config/animation.conf
source = ~/.config/hypr/config/decoration.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/rule.conf
source = ~/.config/hypr/config/general.conf

debug {
	disable_logs=false
	damage_tracking=false
}


gesture {
	gesture = 3, horizontal, workspace, scale: 0.5
	gesture = 3, vertical, dispatcher, hyprexpo:expo, toggle 
}

gestures {
workspace_swipe_distance = 700
}
