bind r
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Reload config
bind -n C-r source-file ~/.tmux.conf

# Window selection like in my hyprland config
bind -n M-q select-window -t 0
bind -n M-w select-window -t 1
bind -n M-e select-window -t 2
bind -n M-r select-window -t 3
bind -n M-t select-window -t 4

# Session Management
bind -n M-f popup -E "~/.config/tmux/bin/switch-session.sh"
bind -n M-Tab switch-client -n
bind -n M-S-Tab switch-client -p

# lazygit
bind -n M-l new-window -c "#{pane_current_path}" "lazygit"

# Window management
bind -n M-c kill-window
bind -n M-j new-window -c "#{pane_current_path}"
bind -n M-n next-window
bind -n M-m previous-window
bind -n M-o popup -E "~/.config/tmux/bin/ff.sh"
# bind -n M-f popup -E "~/.config/tmux/bin/switch-window.sh" 

# Copilot
bind -n M-p run-shell "~/.config/tmux/bin/open-copilot.sh #{pane_current_path}"

# Pane management
bind -n M-s split-window -v -c "#{pane_current_path}"
bind -n M-v split-window -h -c "#{pane_current_path}"
## rotate panes
bind r swap-pane -D
bind -n M-k  kill-pane

bind -n M-, command-prompt -p "Rename window:" "rename-window '%%'"
bind -n M-. command-prompt -p "Rename session:" "rename-session '%%'"

# Copy mode
bind-key -n M-i copy-mode
set-option -g mode-keys vi
bind-key -T copy-mode-vi 'v'   send -X rectangle-off \; send -X begin-selection  # Begin selection in copy mode
bind-key -T copy-mode-vi 'C-v' send -X rectangle-on \; send -X begin-selection   # Begin selection in copy mode
bind-key -T copy-mode-vi 'y'   send -X copy-selection-and-cancel                 # Yank selection in copy mode

bind-key -T copy-mode-vi Escape {
    if-shell -F "#{selection_present}" {
        # true
        send-keys -X clear-selection
    } {
        # false
        send-keys -X cancel
    }
}
