foreground=white
inactive=brightblack
background=default
accent=red
left=blue
right=green


set -g status-interval 1

# set-option -g pane-border-style "fg=${background}"
# set-option -g pane-active-border-style "fg=${accent}"

set-option -g status-position top
set -g window-status-separator ""
set -g status-justify left
set -g status-style "bg=${background},fg=${foreground}"
set -g message-style "bg=${background},fg=${foreground}"
set -g message-command-style "bg=${background},fg=${foreground}"
set -g mode-style "bg=${background},fg=${foreground}"

set -g status-left "#[bg=${background},fg=${left}] #S"

set -g status-right "#[bg=${background},fg=${right}] #(echo '#{pane_current_path}' | ~/.config/tmux/bin/shortpath.sh)"

set -g window-status-format "#[bg=${background},fg=${inactive}] #I:#W"

set -g window-status-current-format "#[bg=${background},fg=${accent},bold] #I:#W"
