foreground=black   
inactive=brightblack
background=black   
accent=red       
left=blue
right=green


set -g status-interval 1

set-option -g pane-border-style "fg=${background}"
set-option -g pane-active-border-style "fg=${accent}"

set-option -g status-position top
set -g window-status-separator ""
set -g status-justify left
set -g status-style "bg=${background},fg=${foreground}"
set -g message-style "bg=${background},fg=${foreground}"
set -g message-command-style "bg=${background},fg=${foreground}"
set -g mode-style "bg=${background},fg=${foreground}"

set -g status-left "#[bg=${left},fg=${background}] #S \
#[bg=${background},fg=${left}]"

set -g status-right "#[fg=${right},bg=${background}]\
 #[bg=${right},fg=${background}]\
 #(echo '#{pane_current_path}' | ~/.config/tmux/bin/shortpath.sh)\
 #[bg=${background},fg=${right}]"

set -g window-status-format "#[bg=${inactive},fg=${background}]\
 #[bg=${inactive},fg=${background}]#I:#W\
 #[default]#[bg=${background},fg=${inactive}]"

set -g window-status-current-format "#[bg=${accent},fg=${background}]\
 #[bg=${accent},fg=${background},bold]#I:#W\
 #[default]#[bg=${background},fg=${accent}]"
