exec-once = hyprpm reload -n
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = hypridle &
exec-once = hyprsunset &
exec-once = waybar &
exec-once = nm-applet &
# exec-once = swaync &
exec-once = swayosd-server &
exec-once = clipse -listen &
exec-once = quickshell &
exec-once = wl-clip-persist --clipboard regular &
exec-once = ~/.config/hypr/bin/wallpaper.sh init &
exec-once = ~/.config/hypr/bin/xdg-portal-restart.sh &
exec-once = ~/.config/hypr/bin/battery_info.sh &
# exec-once = ~/.config/hypr/bin/hintsd &
exec-once = spotify-launcher &
