group {
col.border_active = rgba(70,130,180,1)
col.border_inactive = rgba(30,30,30,1)
  groupbar {
    height = 0
    font_size = 0
    # about half the indicator height
    # Make the indicator tall enough to render text inside
    indicator_height = 0

		text_color = rgba(255,255,255,1)
		text_color_inactive = rgba(200,200,200,1)
		col.active = rgba(70,130,180,1)
		col.inactive = rgba(26,28,29,1)
		rounding = 0
		gaps_out = 0
		gaps_in = 0
  }
}

decoration {
	rounding = 12
  rounding_power = 5
	active_opacity = 1.0
	inactive_opacity = 1.0
	dim_inactive = false
	dim_strength = 0.3
	# screen_shader = ~/.config/hypr/shaders/grayscale.frag

	shadow {
		enabled = true
		range = 3
		render_power = 0
		color = rgba(0,0,0,0.3)
	}

	blur {
		enabled = false
		size = 6
		passes = 3
		ignore_opacity = true
		new_optimizations = true
		noise = 0.01
		contrast = 0.9
		brightness = 0.8
		vibrancy = 0.1696
		popups = true
	}
}
