decoration {
	rounding = 9
  rounding_power = 9
	active_opacity = 1.0
	inactive_opacity = 1.0
	dim_inactive = true
	dim_strength = 0.3

	shadow {
		enabled = true
		range = 10
		render_power = 5
		color = rgba(0,0,0,0.1)
	}

	blur {
		enabled = true
		size = 3
		passes = 3
		ignore_opacity = true
		new_optimizations = true
		noise = 0.0
		contrast = 0.9
		brightness = 0.8
		vibrancy = 0.0
		popups = false
	}
}
