general {
	gaps_in = 3
	gaps_out = 5
	border_size = 0
	col.active_border = rgba(65,72,104,0.3)
	col.inactive_border = rgba(65,72,104,0.1)
	resize_on_border = true
	allow_tearing = false
	layout = scrolling
}

render {
cm_sdr_eotf = 2
}

xwayland {
	force_zero_scaling = true
}


scrolling {
    fullscreen_on_one_column = true
    column_width = 0.5
}


dwindle {
	preserve_split = true
}

misc {
	vrr = 0
	on_focus_under_fullscreen = true
	force_default_wallpaper = false
	exit_window_retains_fullscreen = true
	focus_on_activate = true
	disable_hyprland_logo = true
}

binds {
	movefocus_cycles_fullscreen = true
}
