input {
	kb_layout = us,it
	# kb_options = grp:win_space_toggle,ctrl:nocaps,fkeys:basic_13-24
	kb_options = grp:win_space_toggle,fkeys:basic_13-24
	follow_mouse = 2
	sensitivity = 0.5
	touchpad {
		natural_scroll = true
		scroll_factor = 0.7
	}
}
