#!/bin/bash

MENU=$(mpc playlist | rofi -dmenu -p "Song" -theme generic -monitor -1)

[[ -z "$MENU" ]] && exit

mpc playlist -f '%position% %artist% - %title%' | grep -i "$MENU" | head -n1 | cut - -d " " -f 1 | xargs mpc play