#! /bin/bash


# AUTOSTART

~/.config/bspwm/autostart


# BSPWM RULES
bspc rule -a floating_terminal state=floating rectangle=650x400+0+0 center=true
bspc rule -a drop_terminal state=floating rectangle=650x1070+1265+5
bspc rule -a music_player state=floating rectangle=650x400+0+0 center=true
bspc rule -a bspwm_helper state=floating rectangle=700x650+0+0 center=true
bspc rule -a mplayer2 state=floating
bspc rule -a Nightly state=tiled
bspc rule -a Screenkey manage=off

# USE THIS FOR 144Hz
bspc config pointer_motion_interval 7ms

bspc config border_width         0
bspc config window_gap           5
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false


bspc config active_border_color '#E5E9F0'
bspc config normal_border_color '#E5E9F0'
bspc config focused_border_color '#BF616A'
bspc config presel_feedback_color "#BF616A"
bspc config -m HDMI-0 top_padding 0
bspc config -m DP-0 left_padding 50
bspc config -m DP-0 top_padding 0
bspc config -m DP-0 right_padding 0
bspc config -m DP-0 bottom_padding 0
bspc monitor DP-0 -d 4 5 6
bspc monitor HDMI-0 -d 1 2 3
