term xterm-256color
allow_remote_control true
dynamic_background_opacity true
background_opacity 1
shell_integration no-title
enable_audio_bell no

# bindings
map ctrl+0 send_text all \x1b[48;5u

# font configurations
font_family       JetBrainsMono Nerd Font 
font_size         12
bold_font         auto
italic_font       auto
bold_italic_font  auto
disable_ligatures never

repaint_delay 7
sync_to_monitor yes

# cursor animations
cursor_shape block
cursor_blink false
cursor_trail 10

# internal border
window_padding_width 10 10

foreground #c2c2b0
background #222222

# Black
color0 #222222
color8 #666666

# Red
color1 #685742
color9 #685742

# Green
color2  #5f875f
color10 #5f875f

# Yellow
color3  #b36d43
color11 #b36d43

# Blue
color4  #78824b
color12 #78824b

# Magenta
color5  #bb7744
color13 #bb7744

# Cyan
color6  #c9a554
color14 #c9a554

# White
color7  #d7c483
color15 #d7c483

# Cursor
cursor #5f875f
cursor_text_color #222222

# Selection highlight
selection_foreground none
selection_background #43492a

# The color for highlighting URLs on mouse-over
url_color #c9a554

# Window borders
active_border_color #78824b
inactive_border_color #1c1c1c
bell_border_color #b36d43

# Tab bar
tab_bar_style fade
tab_fade 1
active_tab_foreground   #222222
active_tab_background   #78824b
active_tab_font_style   bold
inactive_tab_foreground #c2c2b0
inactive_tab_background #1c1c1c
inactive_tab_font_style bold
tab_bar_background #151515

# Title bar
macos_titlebar_color #151515

# Storm
# background #24283b
# cursor_text_color #24283b
# active_tab_background   #1f2335
# inactive_tab_background #1f2335
# macos_titlebar_color #1f2335
