term xterm-256color
allow_remote_control true
dynamic_background_opacity true
background_opacity 0.90
shell_integration no-title
enable_audio_bell no

# bindings
map ctrl+0 send_text all \x1b[48;5u

# font configurations
font_family       JetBrainsMono Nerd Font
font_size         12
bold_font         auto
italic_font       auto
bold_italic_font  auto
disable_ligatures never

repaint_delay 7
sync_to_monitor yes

# cursor animations
cursor_shape block
cursor_blink false
cursor_trail 10

# internal border
window_padding_width 10 10

# Colors

# The basic colors
foreground              #ABB2BF
background              #101017
selection_foreground    #282C34
selection_background    #ABB2BF

# Cursor colors
cursor                  #ABB2BF
cursor_text_color       #282C34

# URL underline color when hovering with mouse
url_color               #ABB2BF

# Tab bar colors
active_tab_foreground   #3F4451
active_tab_background   #D7DAE0
inactive_tab_foreground #ABB2BF
inactive_tab_background #282C34

# The 16 terminal colors

# black
color0 #282C34
color8 #4F5666

# red
color1 #E06C75
color9 #BE5046

# green
color2  #98C379
color10 #A5E075

# yellow
color3  #D19A66
color11 #E5C07B

# blue
color4  #61AFEF
color12 #4DC4FF

# purple
color5  #C678DD
color13 #DE73FF

# cyan
color6  #56B6C2
color14 #4CD1E0

# white
color7  #D7DAE0
color15 #E6E6E6
